import type { Metadata } from "next";
import '@/styles/globals.scss';
import { getAllMenus } from '@/utils/lib/menus';
import { getSiteoptions } from "@/utils/lib/siteoptions";

// components
import Layout from '@/components/Layout';

unstable_noStore();

const { menus = [] } = await getAllMenus();
const settings = await getSiteoptions();
const { sidePosts } = await getSidePosts();

// Contexts
import {
    setMenusContext,
    setSiteOptionsContext,
    setSidePostsContext,
} from "@/utils/hooks/ServerContext";
import { getSidePosts } from "@/utils/lib/posts";
import {unstable_noStore} from "next/cache";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    setMenusContext(menus);
    setSiteOptionsContext(settings);
    setSidePostsContext(sidePosts);

    return (
        <html lang="en">
            <body>
                <Layout>
                    {children}
                </Layout>
            </body>
        </html>
    );
}

